"""Set group_name not null default empty string on exams

Revision ID: 5d49433bac11
Revises: 8caffe690b87
Create Date: 2025-06-07 23:05:38.192724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d49433bac11'
down_revision: Union[str, None] = '8caffe690b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # SQLite does not support ALTER COLUMN directly, use batch_alter_table
    with op.batch_alter_table('exams') as batch_op:
        # Set empty string for existing NULLs
        batch_op.execute("UPDATE exams SET group_name = '' WHERE group_name IS NULL")
        # Alter column to not nullable
        batch_op.alter_column('group_name', existing_type=sa.String(20), nullable=False, existing_server_default="")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exams', 'group_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
